services:
  - type: web
    name: global-sante
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
    disk:
      name: global-sante-data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
